<?php

namespace App\Filament\Resources;

use App\Filament\Resources\SupportServiceResource\Pages;
use App\Filament\Resources\SupportServiceResource\RelationManagers;
use App\Models\SupportService;
use Filament\Forms;
use Filament\Forms\Form;
use Filament\Resources\Resource;
use Filament\Tables;
use Filament\Tables\Table;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\SoftDeletingScope;

class SupportServiceResource extends Resource
{
    protected static ?string $model = SupportService::class;

    protected static ?string $navigationIcon = 'heroicon-o-rectangle-stack';

    public static function form(Form $form): Form
    {
        return $form
            ->schema([
                Forms\Components\TextInput::make('service_name')
                    ->required()
                    ->maxLength(255),
                Forms\Components\TextInput::make('service_slug')
                    ->required()
                    ->maxLength(255),
                Forms\Components\Textarea::make('description')
                    ->columnSpanFull(),
                Forms\Components\Textarea::make('detailed_description')
                    ->columnSpanFull(),
                Forms\Components\Toggle::make('administrative_assistance')
                    ->required(),
                Forms\Components\Toggle::make('professional_support')
                    ->required(),
                Forms\Components\Toggle::make('personal_support')
                    ->required(),
                Forms\Components\Toggle::make('social_activities')
                    ->required(),
                Forms\Components\TextInput::make('administrative_services'),
                Forms\Components\Toggle::make('visa_assistance')
                    ->required(),
                Forms\Components\Toggle::make('residence_permit_help')
                    ->required(),
                Forms\Components\Toggle::make('bank_account_assistance')
                    ->required(),
                Forms\Components\Toggle::make('local_registration_help')
                    ->required(),
                Forms\Components\Toggle::make('health_insurance_guidance')
                    ->required(),
                Forms\Components\Toggle::make('document_translation')
                    ->required(),
                Forms\Components\TextInput::make('professional_services'),
                Forms\Components\Toggle::make('company_mediation')
                    ->required(),
                Forms\Components\Toggle::make('corporate_culture_advice')
                    ->required(),
                Forms\Components\Toggle::make('internship_difficulty_support')
                    ->required(),
                Forms\Components\Toggle::make('professional_guidance')
                    ->required(),
                Forms\Components\Toggle::make('cv_linkedin_optimization')
                    ->required(),
                Forms\Components\Toggle::make('interview_preparation')
                    ->required(),
                Forms\Components\TextInput::make('personal_services'),
                Forms\Components\Toggle::make('cultural_integration_help')
                    ->required(),
                Forms\Components\Toggle::make('local_life_recommendations')
                    ->required(),
                Forms\Components\Toggle::make('medical_assistance')
                    ->required(),
                Forms\Components\Toggle::make('personal_difficulties_support')
                    ->required(),
                Forms\Components\Toggle::make('mental_health_support')
                    ->required(),
                Forms\Components\Toggle::make('emergency_assistance')
                    ->required(),
                Forms\Components\TextInput::make('social_activities_offered'),
                Forms\Components\Toggle::make('networking_events')
                    ->required(),
                Forms\Components\Toggle::make('intern_meetups')
                    ->required(),
                Forms\Components\Toggle::make('cultural_outings')
                    ->required(),
                Forms\Components\Toggle::make('team_building_activities')
                    ->required(),
                Forms\Components\TextInput::make('monthly_events_count')
                    ->numeric(),
                Forms\Components\TextInput::make('events_average_cost')
                    ->numeric(),
                Forms\Components\Toggle::make('has_24_7_helpline')
                    ->required(),
                Forms\Components\TextInput::make('emergency_phone')
                    ->tel()
                    ->maxLength(255),
                Forms\Components\TextInput::make('support_email')
                    ->email()
                    ->maxLength(255),
                Forms\Components\Toggle::make('email_support_available')
                    ->required(),
                Forms\Components\TextInput::make('email_response_hours')
                    ->email()
                    ->numeric(),
                Forms\Components\Toggle::make('personal_appointments')
                    ->required(),
                Forms\Components\Toggle::make('video_appointments')
                    ->required(),
                Forms\Components\Toggle::make('mobile_app_available')
                    ->required(),
                Forms\Components\Toggle::make('live_chat_support')
                    ->required(),
                Forms\Components\TextInput::make('whatsapp_support')
                    ->maxLength(255),
                Forms\Components\TextInput::make('urgent_response_hours')
                    ->numeric(),
                Forms\Components\Toggle::make('personalized_advisor')
                    ->required(),
                Forms\Components\Toggle::make('confidential_handling')
                    ->required(),
                Forms\Components\Toggle::make('concrete_solutions_commitment')
                    ->required(),
                Forms\Components\TextInput::make('service_guarantees'),
                Forms\Components\TextInput::make('covered_cities')
                    ->required(),
                Forms\Components\TextInput::make('supported_languages')
                    ->required(),
                Forms\Components\Toggle::make('operates_weekends')
                    ->required(),
                Forms\Components\Toggle::make('operates_holidays')
                    ->required(),
                Forms\Components\TextInput::make('regular_hours_start'),
                Forms\Components\TextInput::make('regular_hours_end'),
                Forms\Components\TextInput::make('advisors_count')
                    ->numeric(),
                Forms\Components\TextInput::make('team_average_experience_years')
                    ->numeric(),
                Forms\Components\TextInput::make('team_specializations'),
                Forms\Components\Toggle::make('multilingual_team')
                    ->required(),
                Forms\Components\Toggle::make('online_resource_library')
                    ->required(),
                Forms\Components\Toggle::make('city_guides_available')
                    ->required(),
                Forms\Components\Toggle::make('document_templates')
                    ->required(),
                Forms\Components\Toggle::make('emergency_contacts_database')
                    ->required(),
                Forms\Components\TextInput::make('mobile_app_store_url')
                    ->maxLength(255),
                Forms\Components\TextInput::make('resource_portal_url')
                    ->maxLength(255),
                Forms\Components\TextInput::make('service_satisfaction_rating')
                    ->numeric(),
                Forms\Components\TextInput::make('total_cases_handled')
                    ->required()
                    ->numeric()
                    ->default(0),
                Forms\Components\TextInput::make('resolution_success_rate')
                    ->numeric(),
                Forms\Components\TextInput::make('average_resolution_hours')
                    ->numeric(),
                Forms\Components\TextInput::make('testimonials'),
                Forms\Components\TextInput::make('monthly_subscription_price')
                    ->numeric(),
                Forms\Components\Toggle::make('included_in_internship_package')
                    ->required(),
                Forms\Components\Toggle::make('pay_per_use_available')
                    ->required(),
                Forms\Components\TextInput::make('consultation_hourly_rate')
                    ->numeric(),
                Forms\Components\TextInput::make('premium_features'),
                Forms\Components\Toggle::make('housing_integration')
                    ->required(),
                Forms\Components\Toggle::make('internship_integration')
                    ->required(),
                Forms\Components\Toggle::make('airport_pickup_coordination')
                    ->required(),
                Forms\Components\Toggle::make('company_liaison')
                    ->required(),
                Forms\Components\Toggle::make('crisis_intervention_available')
                    ->required(),
                Forms\Components\TextInput::make('emergency_protocols'),
                Forms\Components\TextInput::make('local_emergency_contacts'),
                Forms\Components\Toggle::make('family_notification_service')
                    ->required(),
                Forms\Components\Toggle::make('legal_assistance_referral')
                    ->required(),
                Forms\Components\Toggle::make('monthly_progress_reports')
                    ->required(),
                Forms\Components\Toggle::make('case_tracking_system')
                    ->required(),
                Forms\Components\Toggle::make('satisfaction_surveys')
                    ->required(),
                Forms\Components\TextInput::make('survey_frequency_days')
                    ->numeric(),
                Forms\Components\Toggle::make('is_active')
                    ->required(),
                Forms\Components\Toggle::make('is_featured')
                    ->required(),
                Forms\Components\Toggle::make('accepting_new_clients')
                    ->required(),
                Forms\Components\TextInput::make('current_capacity_percentage')
                    ->required()
                    ->numeric()
                    ->default(0.00),
                Forms\Components\TextInput::make('sort_order')
                    ->required()
                    ->numeric()
                    ->default(0),
                Forms\Components\Textarea::make('admin_notes')
                    ->columnSpanFull(),
            ]);
    }

    public static function table(Table $table): Table
    {
        return $table
            ->columns([
                Tables\Columns\TextColumn::make('service_name')
                    ->searchable(),
                Tables\Columns\TextColumn::make('service_slug')
                    ->searchable(),
                Tables\Columns\IconColumn::make('administrative_assistance')
                    ->boolean(),
                Tables\Columns\IconColumn::make('professional_support')
                    ->boolean(),
                Tables\Columns\IconColumn::make('personal_support')
                    ->boolean(),
                Tables\Columns\IconColumn::make('social_activities')
                    ->boolean(),
                Tables\Columns\IconColumn::make('visa_assistance')
                    ->boolean(),
                Tables\Columns\IconColumn::make('residence_permit_help')
                    ->boolean(),
                Tables\Columns\IconColumn::make('bank_account_assistance')
                    ->boolean(),
                Tables\Columns\IconColumn::make('local_registration_help')
                    ->boolean(),
                Tables\Columns\IconColumn::make('health_insurance_guidance')
                    ->boolean(),
                Tables\Columns\IconColumn::make('document_translation')
                    ->boolean(),
                Tables\Columns\IconColumn::make('company_mediation')
                    ->boolean(),
                Tables\Columns\IconColumn::make('corporate_culture_advice')
                    ->boolean(),
                Tables\Columns\IconColumn::make('internship_difficulty_support')
                    ->boolean(),
                Tables\Columns\IconColumn::make('professional_guidance')
                    ->boolean(),
                Tables\Columns\IconColumn::make('cv_linkedin_optimization')
                    ->boolean(),
                Tables\Columns\IconColumn::make('interview_preparation')
                    ->boolean(),
                Tables\Columns\IconColumn::make('cultural_integration_help')
                    ->boolean(),
                Tables\Columns\IconColumn::make('local_life_recommendations')
                    ->boolean(),
                Tables\Columns\IconColumn::make('medical_assistance')
                    ->boolean(),
                Tables\Columns\IconColumn::make('personal_difficulties_support')
                    ->boolean(),
                Tables\Columns\IconColumn::make('mental_health_support')
                    ->boolean(),
                Tables\Columns\IconColumn::make('emergency_assistance')
                    ->boolean(),
                Tables\Columns\IconColumn::make('networking_events')
                    ->boolean(),
                Tables\Columns\IconColumn::make('intern_meetups')
                    ->boolean(),
                Tables\Columns\IconColumn::make('cultural_outings')
                    ->boolean(),
                Tables\Columns\IconColumn::make('team_building_activities')
                    ->boolean(),
                Tables\Columns\TextColumn::make('monthly_events_count')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('events_average_cost')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\IconColumn::make('has_24_7_helpline')
                    ->boolean(),
                Tables\Columns\TextColumn::make('emergency_phone')
                    ->searchable(),
                Tables\Columns\TextColumn::make('support_email')
                    ->searchable(),
                Tables\Columns\IconColumn::make('email_support_available')
                    ->boolean(),
                Tables\Columns\TextColumn::make('email_response_hours')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\IconColumn::make('personal_appointments')
                    ->boolean(),
                Tables\Columns\IconColumn::make('video_appointments')
                    ->boolean(),
                Tables\Columns\IconColumn::make('mobile_app_available')
                    ->boolean(),
                Tables\Columns\IconColumn::make('live_chat_support')
                    ->boolean(),
                Tables\Columns\TextColumn::make('whatsapp_support')
                    ->searchable(),
                Tables\Columns\TextColumn::make('urgent_response_hours')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\IconColumn::make('personalized_advisor')
                    ->boolean(),
                Tables\Columns\IconColumn::make('confidential_handling')
                    ->boolean(),
                Tables\Columns\IconColumn::make('concrete_solutions_commitment')
                    ->boolean(),
                Tables\Columns\IconColumn::make('operates_weekends')
                    ->boolean(),
                Tables\Columns\IconColumn::make('operates_holidays')
                    ->boolean(),
                Tables\Columns\TextColumn::make('regular_hours_start'),
                Tables\Columns\TextColumn::make('regular_hours_end'),
                Tables\Columns\TextColumn::make('advisors_count')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('team_average_experience_years')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\IconColumn::make('multilingual_team')
                    ->boolean(),
                Tables\Columns\IconColumn::make('online_resource_library')
                    ->boolean(),
                Tables\Columns\IconColumn::make('city_guides_available')
                    ->boolean(),
                Tables\Columns\IconColumn::make('document_templates')
                    ->boolean(),
                Tables\Columns\IconColumn::make('emergency_contacts_database')
                    ->boolean(),
                Tables\Columns\TextColumn::make('mobile_app_store_url')
                    ->searchable(),
                Tables\Columns\TextColumn::make('resource_portal_url')
                    ->searchable(),
                Tables\Columns\TextColumn::make('service_satisfaction_rating')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('total_cases_handled')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('resolution_success_rate')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('average_resolution_hours')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('monthly_subscription_price')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\IconColumn::make('included_in_internship_package')
                    ->boolean(),
                Tables\Columns\IconColumn::make('pay_per_use_available')
                    ->boolean(),
                Tables\Columns\TextColumn::make('consultation_hourly_rate')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\IconColumn::make('housing_integration')
                    ->boolean(),
                Tables\Columns\IconColumn::make('internship_integration')
                    ->boolean(),
                Tables\Columns\IconColumn::make('airport_pickup_coordination')
                    ->boolean(),
                Tables\Columns\IconColumn::make('company_liaison')
                    ->boolean(),
                Tables\Columns\IconColumn::make('crisis_intervention_available')
                    ->boolean(),
                Tables\Columns\IconColumn::make('family_notification_service')
                    ->boolean(),
                Tables\Columns\IconColumn::make('legal_assistance_referral')
                    ->boolean(),
                Tables\Columns\IconColumn::make('monthly_progress_reports')
                    ->boolean(),
                Tables\Columns\IconColumn::make('case_tracking_system')
                    ->boolean(),
                Tables\Columns\IconColumn::make('satisfaction_surveys')
                    ->boolean(),
                Tables\Columns\TextColumn::make('survey_frequency_days')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\IconColumn::make('is_active')
                    ->boolean(),
                Tables\Columns\IconColumn::make('is_featured')
                    ->boolean(),
                Tables\Columns\IconColumn::make('accepting_new_clients')
                    ->boolean(),
                Tables\Columns\TextColumn::make('current_capacity_percentage')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('sort_order')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('created_at')
                    ->dateTime()
                    ->sortable()
                    ->toggleable(isToggledHiddenByDefault: true),
                Tables\Columns\TextColumn::make('updated_at')
                    ->dateTime()
                    ->sortable()
                    ->toggleable(isToggledHiddenByDefault: true),
            ])
            ->filters([
                //
            ])
            ->actions([
                Tables\Actions\EditAction::make(),
            ])
            ->bulkActions([
                Tables\Actions\BulkActionGroup::make([
                    Tables\Actions\DeleteBulkAction::make(),
                ]),
            ]);
    }

    public static function getRelations(): array
    {
        return [
            //
        ];
    }

    public static function getPages(): array
    {
        return [
            'index' => Pages\ListSupportServices::route('/'),
            'create' => Pages\CreateSupportService::route('/create'),
            'edit' => Pages\EditSupportService::route('/{record}/edit'),
        ];
    }
}
